#!/bin/sh

. ${0%/*}/functions

testcase() {
	cp otherfile $catchdir/somefile
	should_fail push 127.0.0.1 somefile
	expect_catch digests_do_not_match

	kill_catch # ...to make sure the file is actually written to disk
	           # if catch mistakenly decides to alter it.
	diff otherfile $catchdir/somefile
}

run
