#!/bin/sh

. ${0%/*}/functions

testcase() {
	size=$(wc -c <somefile)
	dd if=somefile of=$catchdir/somefile bs=1 count=$((size/4)) 2>/dev/null
	push 127.0.0.1 somefile
	expect_catch transfer_completed

	kill_catch # ...to make sure the file is actually written to disk.
	diff somefile $catchdir/somefile
}

run
