#!/bin/sh

. ${0%/*}/functions

testcase() {
	cp emptyfile $catchdir/somefile
	push 127.0.0.1 somefile
	expect_catch transfer_completed

	kill_catch # ...to make sure the file is actually written to disk.
	diff somefile $catchdir/somefile
}

run
