#!/bin/sh

. ${0%/*}/functions

testcase() {
	cp otherfile $catchdir/somefile
	should_fail push 127.0.0.1 somefile smallerfile
	expect_catch digests_do_not_match
	expect_catch transfer_completed

	kill_catch # ...to make sure the last file is actually written to disk.
	diff otherfile $catchdir/somefile
	diff smallerfile $catchdir/smallerfile
}

run
