#!/bin/sh

. ${0%/*}/functions

catch_opts=-f

testcase() {
	cp otherfile $catchdir/somefile
	push -f 127.0.0.1 somefile
	expect_catch transfer_completed

	kill_catch # ...to make sure the last file is actually written to disk.
	diff somefile $catchdir/somefile
}

run
